// Mock data for ASALO Logistic dashboard

const ORDER_STATUSES = [
  { key: "new", label: "New", color: "oklch(0.72 0.14 230)" },
  { key: "processing", label: "Processing", color: "oklch(0.78 0.16 75)" },
  { key: "loaded", label: "Loaded", color: "oklch(0.74 0.13 290)" },
  { key: "in_transit", label: "In Transit", color: "oklch(0.76 0.14 200)" },
  { key: "delivered", label: "Delivered", color: "oklch(0.74 0.14 145)" },
  { key: "delayed", label: "Delayed", color: "oklch(0.72 0.18 30)" },
];

const STATUS_FLOW = ["new", "processing", "loaded", "in_transit", "delivered"];

const SMS_TEMPLATES = {
  new: "Hi {name}, your ASALO order {ref} has been received. We'll update you as it moves. Track: asalo.co/t/{ref}",
  processing: "Hi {name}, your ASALO order {ref} is now being processed at our depot.",
  loaded: "Hi {name}, your ASALO order {ref} has been loaded for dispatch.",
  in_transit: "Hi {name}, your ASALO order {ref} is on the way. ETA {eta}. Driver: {driver}.",
  delivered: "Delivered. Your ASALO order {ref} arrived at {time}. Thank you for choosing ASALO.",
  delayed: "Heads up — your ASALO order {ref} is delayed. New ETA {eta}. Sorry for the inconvenience.",
  out_for_delivery: "Out for delivery. Your ASALO order {ref} arrives within ~{window}.",
};

const CARGO_TYPES = ["Pallets", "Parcels", "Barrels", "Cold chain"];

const ORDERS = [
  {
    id: "ASL-24871",
    customer: "Maridale Foods Pty",
    contact: "+61 4 8821 0034",
    contactName: "Renee P.",
    cargo: "Cold chain",
    weight: "1,240 kg",
    items: 18,
    origin: "Melbourne DC",
    destination: "Adelaide — Hindmarsh",
    distance: "726 km",
    status: "new",
    placed: "12 min ago",
    eta: "Tomorrow 14:00",
    value: "$3,420",
    priority: "high",
    temp: "−4°C",
  },
  {
    id: "ASL-24870",
    customer: "Northbridge Wines",
    contact: "+61 4 1188 2210",
    contactName: "Tom K.",
    cargo: "Pallets",
    weight: "2,800 kg",
    items: 12,
    origin: "Sydney Hub",
    destination: "Brisbane — Eagle Farm",
    distance: "915 km",
    status: "processing",
    placed: "38 min ago",
    eta: "Wed 09:30",
    value: "$5,180",
    priority: "normal",
  },
  {
    id: "ASL-24869",
    customer: "Bayer Industrial",
    contact: "+61 4 0099 4412",
    contactName: "Dispatch",
    cargo: "Barrels",
    weight: "4,150 kg",
    items: 24,
    origin: "Perth Yard",
    destination: "Kalgoorlie Site B",
    distance: "595 km",
    status: "loaded",
    placed: "1 h 12 m",
    eta: "Tonight 22:00",
    value: "$2,940",
    priority: "normal",
  },
  {
    id: "ASL-24868",
    customer: "Greenline Grocers",
    contact: "+61 4 5520 1188",
    contactName: "Alicia M.",
    cargo: "Parcels",
    weight: "180 kg",
    items: 64,
    origin: "Melbourne DC",
    destination: "Geelong West",
    distance: "78 km",
    status: "in_transit",
    placed: "2 h 04 m",
    eta: "Today 16:20",
    value: "$640",
    priority: "normal",
    driver: "K. Daniels — Truck 14",
    progress: 0.62,
  },
  {
    id: "ASL-24867",
    customer: "Coastal Seafoods",
    contact: "+61 4 7710 0921",
    contactName: "Renji P.",
    cargo: "Cold chain",
    weight: "920 kg",
    items: 40,
    origin: "Hobart Port",
    destination: "Launceston Market",
    distance: "200 km",
    status: "in_transit",
    placed: "3 h 41 m",
    eta: "Today 13:50",
    value: "$1,810",
    priority: "high",
    driver: "M. Okafor — Truck 07",
    progress: 0.84,
    temp: "−2°C",
  },
  {
    id: "ASL-24866",
    customer: "Apex Building Supply",
    contact: "+61 4 3322 5588",
    contactName: "Site office",
    cargo: "Pallets",
    weight: "6,200 kg",
    items: 9,
    origin: "Brisbane Hub",
    destination: "Toowoomba — East",
    distance: "127 km",
    status: "delayed",
    placed: "5 h 12 m",
    eta: "Today 18:30 (+2h)",
    value: "$1,260",
    priority: "high",
    note: "Traffic incident on M2",
  },
  {
    id: "ASL-24865",
    customer: "Bright Pharma",
    contact: "+61 4 8800 4221",
    contactName: "Ops",
    cargo: "Cold chain",
    weight: "340 kg",
    items: 22,
    origin: "Sydney Hub",
    destination: "Newcastle Med Centre",
    distance: "162 km",
    status: "delivered",
    placed: "Yesterday",
    eta: "Yesterday 15:10",
    value: "$2,260",
    priority: "normal",
    temp: "+2°C",
  },
  {
    id: "ASL-24864",
    customer: "Maridale Foods Pty",
    contact: "+61 4 8821 0034",
    contactName: "Renee P.",
    cargo: "Pallets",
    weight: "1,800 kg",
    items: 14,
    origin: "Melbourne DC",
    destination: "Bendigo Depot",
    distance: "151 km",
    status: "delivered",
    placed: "Yesterday",
    eta: "Yesterday 11:40",
    value: "$1,090",
    priority: "normal",
  },
];

const DRIVERS = [
  { id: "drv-014", name: "K. Daniels", truck: "Truck 14", phone: "+61 4 8800 1144", status: "on_route", route: "Melbourne → Geelong", load: 0.62, hours: "5h 20m / 12h" },
  { id: "drv-007", name: "M. Okafor", truck: "Truck 07", phone: "+61 4 8800 1077", status: "on_route", route: "Hobart → Launceston", load: 0.84, hours: "3h 10m / 12h" },
  { id: "drv-022", name: "S. Whittaker", truck: "Truck 22", phone: "+61 4 8800 1022", status: "loading", route: "Perth Yard", load: 0.0, hours: "0h 40m / 12h" },
  { id: "drv-031", name: "L. Marin", truck: "Truck 31", phone: "+61 4 8800 1031", status: "available", route: "Sydney Hub", load: 0.0, hours: "0h 00m / 12h" },
  { id: "drv-008", name: "J. Pham", truck: "Truck 08", phone: "+61 4 8800 1008", status: "rest", route: "Adelaide", load: 0.0, hours: "11h 50m / 12h" },
  { id: "drv-019", name: "R. Iqbal", truck: "Truck 19 (Reefer)", phone: "+61 4 8800 1019", status: "available", route: "Melbourne DC", load: 0.0, hours: "1h 15m / 12h" },
];

const SMS_LOG = [
  { ts: "14:42", to: "+61 4 7710 0921", ref: "ASL-24867", trigger: "in_transit", status: "delivered", preview: "Hi Renji, your ASALO order ASL-24867 is on the way. ETA Today 13:50. Driver: M. Okafor." },
  { ts: "14:31", to: "+61 4 5520 1188", ref: "ASL-24868", trigger: "in_transit", status: "delivered", preview: "Hi Alicia, your ASALO order ASL-24868 is on the way. ETA Today 16:20." },
  { ts: "14:18", to: "+61 4 0099 4412", ref: "ASL-24869", trigger: "loaded", status: "delivered", preview: "Hi Dispatch, your ASALO order ASL-24869 has been loaded for dispatch." },
  { ts: "13:56", to: "+61 4 1188 2210", ref: "ASL-24870", trigger: "processing", status: "delivered", preview: "Hi Tom, your ASALO order ASL-24870 is now being processed at our depot." },
  { ts: "13:44", to: "+61 4 8821 0034", ref: "ASL-24871", trigger: "new", status: "delivered", preview: "Hi Renee, your ASALO order ASL-24871 has been received." },
  { ts: "13:12", to: "+61 4 3322 5588", ref: "ASL-24866", trigger: "delayed", status: "delivered", preview: "Heads up — your ASALO order ASL-24866 is delayed. New ETA Today 18:30." },
  { ts: "12:40", to: "+61 4 8800 4221", ref: "ASL-24865", trigger: "delivered", status: "delivered", preview: "Delivered. Your ASALO order ASL-24865 arrived at 15:10. Thank you." },
  { ts: "11:08", to: "+61 4 8821 0034", ref: "ASL-24864", trigger: "delivered", status: "failed", preview: "Delivered. Your ASALO order ASL-24864 arrived at 11:40." },
];

const CUSTOMERS = [
  { name: "Maridale Foods Pty", contact: "Renee P.", phone: "+61 4 8821 0034", orders: 142, value: "$184k", tier: "Enterprise" },
  { name: "Northbridge Wines", contact: "Tom K.", phone: "+61 4 1188 2210", orders: 88, value: "$96k", tier: "Pro" },
  { name: "Bayer Industrial", contact: "Dispatch", phone: "+61 4 0099 4412", orders: 64, value: "$71k", tier: "Pro" },
  { name: "Greenline Grocers", contact: "Alicia M.", phone: "+61 4 5520 1188", orders: 312, value: "$118k", tier: "Enterprise" },
  { name: "Coastal Seafoods", contact: "Renji P.", phone: "+61 4 7710 0921", orders: 47, value: "$52k", tier: "Standard" },
  { name: "Apex Building Supply", contact: "Site office", phone: "+61 4 3322 5588", orders: 28, value: "$38k", tier: "Standard" },
  { name: "Bright Pharma", contact: "Ops", phone: "+61 4 8800 4221", orders: 76, value: "$140k", tier: "Pro" },
];

Object.assign(window, {
  ORDER_STATUSES,
  STATUS_FLOW,
  SMS_TEMPLATES,
  CARGO_TYPES,
  ORDERS,
  DRIVERS,
  SMS_LOG,
  CUSTOMERS,
});
